[package]
name = "orange_terminal_binding"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "orange_terminal_binding"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.31.0"
crossterm = "0.27.0"
libc = "0.2.153"
